export { default as xAPI } from './xAPI.setup'
export * from './xAPI.statements'
export * from './getActor'
export * from './getVerb'
export * from './getObject'
export * from './getContext'
export * from './Statement.hooks'
