#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn test
yarn run ts-node src/shared/auto-order-json-translations.ts
yarn lint
npx typedoc
# force copy contents of docs folder to wiki folder:
cp -rf docs/* wiki/
# remove docs folder:
rm -rf docs